# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Vagrant Box
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |vb|
    vb.name = "GitLab"
    vb.memory = 2048
    vb.cpus = 8
  end

  # Salt Provisioner
  config.vm.provision :salt do |salt|
    # Relative location of configuration file to use for minion
    # since we need to tell our minion to run in masterless mode
    salt.minion_config = "saltstack/etc/minion"

    # On provision, run state.highstate (which installs packages, services, etc).
    # Highstate basicly means "compare the VMs current machine state against
    # what it should be and make changes if necessary".
    salt.run_highstate = true

    # Run in verbose mode, so it will output all debug info to the console.
    salt.verbose = true
  end

  config.vm.network "public_network", ip: "192.168.0.17"
end
