# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Vagrant Box
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |vb, override|
    vb.name = "GitLab"
    vb.memory = 2048
    vb.cpus = 8

    override.vm.network "public_network", ip: "192.168.0.17", bridge: "Realtek PCIe GBE Family Controller"
  end

  config.vm.provider :openstack do |os, override|
    # Credentials
    os.username           = 'admin'
    os.password           = 'hop'
    os.tenant_name        = 'demo'
    os.openstack_auth_url = 'http://192.168.27.100:5000/v2.0'

    # VM Config
    os.server_name        = 'vagrant-test'
    os.flavor             = 'm1.small'
    os.image              = 'ubuntu/trusty64'
    os.security_groups    = ['default']

    # Floating IPs
    os.floating_ip_pool   = 'public'

    # SSH authentication
    os.keypair_name       = 'admin'
    os.ssh_timeout        = 400

    override.vm.provision "shell", path: "update_dns.sh"

    override.ssh.username         = 'ubuntu'
    override.ssh.private_key_path = "../OpenStack/saltstack/salt/openstack/id_rsa"
  end

  # Salt Provisioner
  config.vm.provision :salt do |salt|
    # Relative location of configuration file to use for minion
    # since we need to tell our minion to run in masterless mode
    salt.minion_config = "saltstack/etc/minion"

    # On provision, run state.highstate (which installs packages, services, etc).
    # Highstate basicly means "compare the VMs current machine state against
    # what it should be and make changes if necessary".
    salt.run_highstate = true

    # Run in verbose mode, so it will output all debug info to the console.
    salt.verbose = true
  end

end
