require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username         = 'cirros'
  config.ssh.private_key_path = "../OpenStack/saltstack/salt/openstack/id_rsa"

  config.vm.provider :openstack do |os|
    # Credentials
    os.username           = 'admin'
    os.password           = 'hop'
    os.tenant_name        = 'demo'
    os.openstack_auth_url = 'http://192.168.27.100:5000/v2.0'

    # VM Config
    os.server_name        = 'vagrant-test'
    os.flavor             = 'm1.tiny'
    os.image              = 'cirros-0.3.4-x86_64-uec'
    os.security_groups    = ['default']

    # Floating IPs
    os.floating_ip_pool   = 'public'

    # SSH authentication
    os.keypair_name       = 'admin'
  end
end
