VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "hop-openstack"

  # eth1, this will be the endpoint
  config.vm.network :private_network, ip: "192.168.27.100"
  # eth2, this will be the OpenStack "public" network
  # ip and subnet mask should match floating_ip_range var in devstack.yml
  config.vm.network :private_network, ip: "172.24.4.225", :netmask => "255.255.255.0", :auto_config => false

  config.vm.provider :virtualbox do |vb|
    vb.name = "OpenStack"
    vb.memory = 8196
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
  end

  config.vm.provision :salt do |salt|
    salt.minion_config = "saltstack/etc/minion"
    salt.run_highstate = true
    salt.grains({
      floating_range: '172.24.4.0/24'
    })
  end

end
